[tool.poetry]
name = "os-helper"
version = "1.1.0"
description = "Utility functions for system operations"
authors = ["Votre Nom <bachir.zerroug.ai@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/warith-harchaoui/os-helper"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.21"
pyyaml = "^6.0"
psutil = "^5.8"
pandas = "^1.3"
pywin32 = { version = "^301", markers = "platform_system == 'Windows'" }

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0"
black = "^22.1"
isort = "^5.10"
flake8 = "^4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
